**Numpy**

In [1]:
import numpy as np



In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
#dimensions and shape of an array
arr.ndim

1

In [7]:
a=np.array([])
b=np.array([[]])


In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
arr.shape

(3,)

In [11]:
#instead of for loopes in list,we can use arange
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#skipping two values
ar=np.arange(0,10,2)
ar

array([0, 2, 4, 6, 8])

In [14]:
#for evenly spaces
ar=np.linspace(0,1,5)
ar

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
#logarithmic scale array
arr=np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [17]:
#array full of zeroes
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [19]:
arr=np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#array full of ones
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [21]:
arr=np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#create a array full of any values
arr=np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
arr=np.full([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [25]:
#uninitialized array
arr=np.empty(5)
arr


array([1., 1., 1., 1., 1.])

In [26]:
arr=np.empty([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#random numbers-float
arr=np.random.randn(2,3)
arr

array([[0.49169714, 0.84830984, 0.9270191 ],
       [1.69936526, 0.69391058, 0.80226444]])

In [29]:
#random numbers-int
arr=np.random.randint(1,10)
arr

5

In [30]:
arr=np.random.randint(1,10,[2,3])
arr

array([[5, 5, 8],
       [7, 9, 7]])

In [31]:
#numpy datatypes
arr=np.array([1,2,3])
arr.dtype

dtype('int64')

In [32]:
print(type(arr))

<class 'numpy.ndarray'>


In [33]:
#converting
lst=["string",1,2,5.6]
arr=np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [34]:
arr.dtype

dtype('<U32')

In [35]:
#typecasting-astype
arr=np.array([1,2,3])
arr=arr.astype(np.float64)
arr

array([1., 2., 3.])

In [37]:
#type casting errors
arr=np.array(["string",1,2,3])
arr=arr.astype(np.int64)
arr

ValueError: invalid literal for int() with base 10: np.str_('string')

In [39]:
#array reshaping-reshape,ravel,flatten
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)#2rows,3columns
print(arr)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [40]:
#ravel-convert into 1D array
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
ravelled=reshaped.ravel()
print(arr)
print(reshaped)
print(ravelled)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [41]:
#flatten-convert into 1D array but it returns the copy of the array
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
flattened=reshaped.flatten()
print(arr)
print(reshaped)
print(flattened)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [42]:
#arithmetic operations on array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [43]:
#universal functions
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [44]:
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [45]:
#indexing and slicing
a=[1,2,3,4,5]
a[-1:-4]

[]

In [46]:
a[-1:-4:-1]

[5, 4, 3]

In [47]:
a[: : 2]

[1, 3, 5]

In [48]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [50]:
print(matrix[1: ,1:])

[[5 6]
 [8 9]]


In [51]:
#Index Arrays-np.take
arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))


[10 30]


In [52]:
#iterating with nditer
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 

In [53]:
#ndenumerate()-both index+value
for ind,x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [54]:
#Views VS Copies
arr = np.array([1, 2, 3, 4, 5])

# Creating a view
view_arr = arr.view()
print("Original array:", arr)
print("View array:", view_arr)

# Modifying the view affects the original array
view_arr[0] = 100
print("\nAfter modifying view_arr[0] = 100:")
print("Original array:", arr)
print("View array:", view_arr)

# Creating a copy
copy_arr = arr.copy()
print("\nOriginal array (after view modification):", arr)
print("Copy array:", copy_arr)

# Modifying the copy does NOT affect the original array
copy_arr[1] = 200
print("\nAfter modifying copy_arr[1] = 200:")
print("Original array:", arr)
print("Copy array:", copy_arr)

Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]

After modifying view_arr[0] = 100:
Original array: [100   2   3   4   5]
View array: [100   2   3   4   5]

Original array (after view modification): [100   2   3   4   5]
Copy array: [100   2   3   4   5]

After modifying copy_arr[1] = 200:
Original array: [100   2   3   4   5]
Copy array: [100 200   3   4   5]


In [56]:
#transpose
arr=np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [57]:
#Swapaxes
arr=np.array([[1,2],[3,4]])
print(arr.swapaxes(0,1))

[[1 3]
 [2 4]]


In [61]:
arr=np.array([[1,2],[3,4]])
print(arr.swapaxes(1,1))

[[1 2]
 [3 4]]


In [62]:
#Concatenation
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [63]:
#Vstack
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
#Hstack
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
#stack
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.stack((a,b),axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [66]:
#Splitting the array
arr=np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [67]:
#hsplit
arr=np.array([[1,2],[3,4],[5,6]])
print(np.hsplit(arr,2))

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [68]:
#repeating
arr=np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [69]:
#tile
arr=np.array([1,2,3])
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


In [71]:
#Aggreagate Functions
arr=np.array([1,2,3])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))

6
2.0
2.0
0.816496580927726
0.6666666666666666
1


In [73]:
#Cumulative Operations
arr=np.array([1,2,3])
print(np.cumsum(arr))
print(np.cumprod(arr))

[1 3 6]
[1 2 6]


In [75]:
#Conditional Based
result=np.where(arr<2,"low","high")
result

array(['low', 'high', 'high'], dtype='<U4')

In [76]:
#Argwhere
print(np.argwhere(arr>1))

[[1]
 [2]]


In [77]:
print(np.logical_and(arr>2,arr<3))

[False False False]


In [78]:
print(np.logical_or(arr>2,arr<3))

[ True  True  True]


In [79]:
#nonzeroes
arr=np.array([0,1,5,0,5])
print(np.nonzero(arr))

(array([1, 2, 4]),)


In [80]:
#broadcasting

# Broadcasting with a scalar
arr_scalar = np.array([1, 2, 3])
scalar = 2
result_scalar = arr_scalar * scalar
print("Array multiplied by scalar:", result_scalar)

# Broadcasting with arrays of different shapes
arr_a = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
arr_b = np.array([10, 20, 30])         # Shape (3,)

result_array = arr_a + arr_b
print("\nArrays added with broadcasting:")
print("arr_a (shape 2,3):\n", arr_a)
print("arr_b (shape 3,):", arr_b)
print("Result:\n", result_array)

# Another example: column vector broadcasting
arr_c = np.array([[100], [200]]) # Shape (2, 1)
result_col_vec = arr_a + arr_c
print("\nArray added with column vector broadcasting:")
print("arr_a (shape 2,3):\n", arr_a)
print("arr_c (shape 2,1):\n", arr_c)
print("Result:\n", result_col_vec)

Array multiplied by scalar: [2 4 6]

Arrays added with broadcasting:
arr_a (shape 2,3):
 [[1 2 3]
 [4 5 6]]
arr_b (shape 3,): [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]

Array added with column vector broadcasting:
arr_a (shape 2,3):
 [[1 2 3]
 [4 5 6]]
arr_c (shape 2,1):
 [[100]
 [200]]
Result:
 [[101 102 103]
 [204 205 206]]


In [82]:
#Vectorization

import time

# Non-vectorized approach (using a loop)
list_a = list(range(1000000))
list_b = list(range(1000000))
result_list = []

start_time = time.time()
for i in range(len(list_a)):
    result_list.append(list_a[i] + list_b[i])
end_time = time.time()
print(f"Time taken for non-vectorized operation: {end_time - start_time:.6f} seconds")

# Vectorized approach (using NumPy arrays)
numpy_a = np.array(range(1000000))
numpy_b = np.array(range(1000000))

start_time = time.time()
result_numpy = numpy_a + numpy_b
end_time = time.time()
print(f"Time taken for vectorized operation: {end_time - start_time:.6f} seconds")

print("\nFirst 5 elements of non-vectorized result:", result_list[:5])
print("First 5 elements of vectorized result:", result_numpy[:5])

Time taken for non-vectorized operation: 0.120707 seconds
Time taken for vectorized operation: 0.001223 seconds

First 5 elements of non-vectorized result: [0, 2, 4, 6, 8]
First 5 elements of vectorized result: [0 2 4 6 8]


In [83]:
#isnan,isinf,isfinite

import numpy as np

arr_with_special_values = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print("Original array:", arr_with_special_values)

# Check for NaN (Not a Number)
print("Is NaN:", np.isnan(arr_with_special_values))

# Check for positive or negative infinity
print("Is Infinite:", np.isinf(arr_with_special_values))

# Check for finite values (not NaN and not infinity)
print("Is Finite:", np.isfinite(arr_with_special_values))

Original array: [  1.   0.  nan  inf -inf   5.]
Is NaN: [False False  True False False False]
Is Infinite: [False False False  True  True False]
Is Finite: [ True  True False False False  True]
